// <auto-generated />
namespace PWebTudoDeNovo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class testefinal2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(testefinal2));
        
        string IMigrationMetadata.Id
        {
            get { return "202101120056132_testefinal2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
